### ISSUE TITLE
Enhancement - Product Listing: Add animated loader icon when filtering products

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Alice-Clothing#107]
Ref: http://fortawesome.github.io/Font-Awesome/examples/

When filtering, it display a blank body page.
![image](https://cloud.githubusercontent.com/assets/12888048/14448048/d84a9e00-0097-11e6-9177-6e62a5fb426e.png)

**Comment by joancapuyan** [comment]
Currently it has an animated loader.
