### ISSUE TITLE
Product Sidebar: Incorrect product filtering. Filter by color and/or size.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Alice-Clothing#108]
"Product Complete...." should not be display as result.

![image](https://cloud.githubusercontent.com/assets/12888048/14448790/81206720-009e-11e6-82b7-6de81f53ce23.png)

**Comment by jsemblantetitanweb** [comment]
This is not a bug. The filter is base on the Attribute value of the product. Even if the attribute value is not use in the variations it would still be filtered according to the values inputted on the attribute section.
