### ISSUE TITLE
Banner: Responsive error

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Alice-Clothing#113]
![image](https://cloud.githubusercontent.com/assets/12888048/14451451/ccfa981c-00b9-11e6-96c5-fa4eb5cfbd80.png)
![image](https://cloud.githubusercontent.com/assets/12888048/14451463/eb2b331e-00b9-11e6-87b2-4cf5b0a17d5e.png)
![image](https://cloud.githubusercontent.com/assets/12888048/14451460/e18ab03c-00b9-11e6-8caf-f883ab026f59.png)

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/14451460/e18ab03c-00b9-11e6-8caf-f883ab026f59.png)

**Comment by joancapuyan** [comment]
User error. The user should upload image of the required dimension W:2000px H: 876px so that the banner description will stay at the center of the image.

**Comment by romatitan** [comment]
320px - 615px full title was display
