### ISSUE TITLE
Request a Quote: After clicking the "Add Another Product" button, it loads the page as if it is a Submit button.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Alice-Clothing#119]
Step to Replicate:
1. Go to Request A Quote page
2. Click " Add Another Product" button
3. Observe that after clicking the button, it loads the page.
4. Observe the highlighted fields as if the form was submitted and prompting error message

**Comment by jsemblantetitanweb** [comment]
This is the behavior of the plugin.
