### ISSUE TITLE
Product Single: Responsive Errors

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Alice-Clothing#121]
![image](https://cloud.githubusercontent.com/assets/12888048/14453639/a2090652-00c8-11e6-98b6-c88be9195064.png)

![image](https://cloud.githubusercontent.com/assets/12888048/14454031/e7ac5572-00ca-11e6-9f44-f0b39599ead3.png)

![image](https://cloud.githubusercontent.com/assets/12888048/14453647/afaa94ec-00c8-11e6-8d13-4191fbd96953.png)

![image](https://cloud.githubusercontent.com/assets/12888048/14453656/b236c488-00c8-11e6-975c-fde584e88ae9.png)

![image](https://cloud.githubusercontent.com/assets/12888048/14453659/b4805f2e-00c8-11e6-988f-f6c6aad6609b.png)

![image](https://cloud.githubusercontent.com/assets/12888048/14453661/b6da3bbe-00c8-11e6-9b9a-14393ac60d03.png)

![image](https://cloud.githubusercontent.com/assets/12888048/14453665/b9de2bea-00c8-11e6-886f-ee8c88629605.png)

![image](https://cloud.githubusercontent.com/assets/12888048/14453666/bc7be202-00c8-11e6-8f26-d174a7457fbf.png)

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/14694650/278879ea-079d-11e6-881c-89453e628cf5.png)

**Comment by iteano** [comment]
There were still items that were not fixed.
1. "Brand" tab section floating.
2. Price clipped.
