### ISSUE TITLE
Homepage/Products: W3C Errors

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Alice-Clothing#128]
**Homepage:**
https://validator.w3.org/nu/?doc=http%3A%2F%2Faliceclothing-2016.stage.titanweb.com.au%2F
![image](https://cloud.githubusercontent.com/assets/12888048/14628692/cd93188e-0632-11e6-8513-c11c6e74f799.png)

**Product Listing:**
https://validator.w3.org/nu/?doc=http%3A%2F%2Faliceclothing-2016.stage.titanweb.com.au%2Fproduct-category%2Fproduct-category-1-title-goes-here-for-this-long%2Fproduct-sub-category-1%2Fproduct-inner-sub-category-title-goes-here-for-this-long%2F
![image](https://cloud.githubusercontent.com/assets/12888048/14628696/d280512c-0632-11e6-812d-2b3ffaae54a6.png)

**Product Single:**
https://validator.w3.org/nu/?doc=http%3A%2F%2Faliceclothing-2016.stage.titanweb.com.au%2Four-products%2Fpolo-shirts%2Fproduct-complete-title-goes-here-for-2-lines-only-title-goes-here-for-2-lines-only-title-goes-here-for-2-lines-only%2F
![image](https://cloud.githubusercontent.com/assets/12888048/14628697/d6118eb4-0632-11e6-83b3-9412fbf05498.png)

**Comment by jsemblantetitanweb** [comment]
This errors are caused by the plugin.

**Comment by romatitan** [comment]
Kindly check the screenshots.
