### ISSUE TITLE
Wishlist: W3C Errors

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Alice-Clothing#130]
**Create a List:**
https://validator.w3.org/nu/?doc=http%3A%2F%2Faliceclothing-2016.stage.titanweb.com.au%2Fmy-lists%2Fcreate-a-list%2F

**Find a List:**
https://validator.w3.org/nu/?doc=http%3A%2F%2Faliceclothing-2016.stage.titanweb.com.au%2Fmy-lists%2Ffind-a-list%2F

**Comment by joancapuyan** [comment]
The remaining errors are caused by the wishlist plugin.

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/14662582/28bc966a-06ea-11e6-9e38-f2fe05d8b903.png)

**Comment by joancapuyan** [comment]
Error #8 is a plugin issue.
