### ISSUE TITLE
Pre Footer: If possible, from 768px - 1199px align the "Follow Us" social media section with the Contact Us and Newsletter.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Alice-Clothing#148]
![pre footer 01 enhancement](https://cloud.githubusercontent.com/assets/12888048/14696070/a89b8308-07aa-11e6-8701-226044a7fbb8.jpg)

**Comment by iteano** [comment]
Verified enhancement implemented. Thanks.
