### ISSUE TITLE
Wishlist: After submitting the form, it prompts an error message "**_Unable to send mail. Please check you values and try again._**" . But, there's no indication that a field/s is required.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Alice-Clothing#160]
Ensure that the Name and Email fields are set as ‘Required’. 
There's no error prompt in the **form** (Share via e-mail).

![wishlist 02](https://cloud.githubusercontent.com/assets/12888048/14697049/2525e3de-07b3-11e6-84c5-8a8440f3abf6.jpg)

**Comment by jsemblantetitanweb** [comment]
Plugin Issue
