### ISSUE TITLE
Wishlist: Form can be submit even the Name field has no value

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Alice-Clothing#161]
Related issue: #160
 Ensure that the Name and Email fields are set as ‘Required’. 
![wishlist 03](https://cloud.githubusercontent.com/assets/12888048/14697080/54bd8336-07b3-11e6-9941-7d61a6e6c6c5.jpg)

**Comment by jsemblantetitanweb** [comment]
This is a plugin issue.

**Comment by romatitan** [comment]
Wishlist - Manage List settings: The Name (First Name and Last Name)  was set as required
