### ISSUE TITLE
Wishlist - Find List: Shared wishlist did not appear on the result

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Alice-Clothing#165]
![wishlist 08](https://cloud.githubusercontent.com/assets/12888048/14697825/352da850-07ba-11e6-856b-bf7bcffe59ab.jpg)
![wishlist 08a](https://cloud.githubusercontent.com/assets/12888048/14697826/36395a5a-07ba-11e6-8145-1145846bdf27.jpg)

**Comment by jsemblantetitanweb** [comment]
This is a plugin behavior. If the wishlist setting is set into public it is searchable but if it is set either shared or private it is not searchable.
