### ISSUE TITLE
Request a quote & Product Single (Variable) : Change dropdown hover color.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Alice-Clothing#178]
![7a](https://cloud.githubusercontent.com/assets/18256652/14810958/244ea0f4-0bc8-11e6-9f7b-846b691dea29.png)

**Comment by iteano** [comment]
**Product Single - Variable**

![7b](https://cloud.githubusercontent.com/assets/18256652/14812207/bc4cb91c-0bce-11e6-93a1-a802a70633a6.png)

**Comment by joancapuyan** [comment]
Cannot be fixed.
