### ISSUE TITLE
Pre-Footer: Lead-ins hover/active state was not implemented

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Alice-Clothing#23]

**Comment by jsemblantetitanweb** [comment]
Lead-ins in the homepage already have there own hover effect.

**Comment by romatitan** [comment]
Kindly check again.
![image](https://cloud.githubusercontent.com/assets/12888048/14631785/b5cb2790-0647-11e6-9c79-0fbc159ddc64.png)
