### ISSUE TITLE
Product Listing: "Add to Wishlist" did not display on variable product

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Alice-Clothing#46]
Screenshot: http://www.awesomescreenshot.com/image/1113621/cc573da035a3ca48c92d1ab3e28c1328

**Comment by joancapuyan** [comment]
It is the plugin behavior, cannot add to wishlist if product is variable type you need to choose product variation first.

**Comment by romatitan** [comment]
Plugin issues
