### ISSUE TITLE
Product Single: Size selection Menu was not implemented

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Alice-Clothing#52]
![image](https://cloud.githubusercontent.com/assets/12888048/14072784/200746ce-f4f6-11e5-8fc8-1215f4d43cdb.png)

![image](https://cloud.githubusercontent.com/assets/12888048/14072400/affa9c58-f4f2-11e5-9ec8-282f1c7022b2.png)

**Comment by joancapuyan** [comment]
It can only be seen if the product is a variable type i.e. http://aliceclothing-2016.stage.titanweb.com.au/our-products/polo-shirts/product-title-goes-here-for-two-lines-or-more/
