### ISSUE TITLE
Product Single: Colour selection Menu was not implemented 

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Alice-Clothing#55]
![image](https://cloud.githubusercontent.com/assets/12888048/14072779/195cc538-f4f6-11e5-9d1b-f05d9506b3ac.png)

![image](https://cloud.githubusercontent.com/assets/12888048/14072400/affa9c58-f4f2-11e5-9ec8-282f1c7022b2.png)

**Comment by joancapuyan** [comment]
It can only be seen if the product is a variable type.

http://aliceclothing-2016.stage.titanweb.com.au/our-products/polo-shirts/product-title-goes-here-for-two-lines-or-more/
