### ISSUE TITLE
Product Single: For variable products, there's no padding top for variable options

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Alice-Clothing#66]
![image](https://cloud.githubusercontent.com/assets/12888048/14073499/5397767a-f4fc-11e5-80c5-eaee8bffd1de.png)

**Comment by romatitan** [comment]
Apply fixes on Brand, Color, and sizes selection.
![image](https://cloud.githubusercontent.com/assets/12888048/14373216/301c43ca-fd7a-11e5-87fd-db36ebbda6a2.png)

**Comment by marjorietitan** [comment]
Unfortunately, chrome browser do not support styling/css for options tags.
