### ISSUE TITLE
Product Single: Missing "Quantity" label for out of stock product

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Alice-Clothing#68]
http://aliceclothing-2016.stage.titanweb.com.au/our-products/product-category-4-logo-wide/product-logo-long/

![untitled](https://cloud.githubusercontent.com/assets/12888048/14073632/4d473fd4-f4fd-11e5-8a40-69c031805f1d.png)

**Comment by joancapuyan** [comment]
It is the woocommerce default behavior.
