### ISSUE TITLE
Product Single: Empty product description tab section was displayed

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Alice-Clothing#83]
![image](https://cloud.githubusercontent.com/assets/12888048/14415081/d3ae1be4-ffcd-11e5-9abe-a2f37809704a.png)

**Comment by jsemblantetitanweb** [comment]
This is already fix. The bug is visible on the products that was created before the fix code was added to the function. But when you create new products and make some test, the bug is not visible.

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/14630673/b7a5dab6-0641-11e6-9a55-97a15d1fe34d.png)
