### ISSUE TITLE
Sign Up: Email Sender Options  "From" Name and  "From" Address

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Alice-Clothing#87]
![image](https://cloud.githubusercontent.com/assets/12888048/14415584/71a36016-ffd3-11e5-92eb-42de26c11e65.png)

**Comment by jsemblantetitanweb** [comment]
It will send another email with this layout 

![image](https://cloud.githubusercontent.com/assets/18159491/14591577/82b54540-0546-11e6-9671-2174d16463f2.png)

**Comment by romatitan** [comment]
Kindly check again the Email / Sign up notification sent to the customer

![image](https://cloud.githubusercontent.com/assets/12888048/14630764/3a7d87cc-0642-11e6-800d-c98976ef6898.png)

**Comment by jsemblantetitanweb** [comment]
Plugin Issue
