### ISSUE TITLE
Product Listing: Zero price was displayed of variable products

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Alice-Clothing#88]
Note: Added variation without price
![image](https://cloud.githubusercontent.com/assets/12888048/14417701/b394bfa8-ffea-11e5-8d7d-1785b21297b1.png)

**Comment by jsemblantetitanweb** [comment]
This is a plugin behavior. User should input price for the variations when the product data is being set into a variable product. 

Note: The (regular price) field in the variation is required.

**Comment by romatitan** [comment]
Plugin issue.
