### ISSUE TITLE
Product Single: Stock Status was saved as "Out of Stock" instead of In stock.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Alice-Clothing#93]
1. Select "Manage stock?" check box 
2. Set the Stock Status to "In stock", then save changes.
3. Observe that the Stock Status was saved as "Out of Stock" instead of In stock.

http://aliceclothing-2016.stage.titanweb.com.au/our-products/polo-shirts/product-complete-title-goes-here-for-2-lines-only-title-goes-here-for-2-lines-only-title-goes-here-for-2-lines-only/

![image](https://cloud.githubusercontent.com/assets/12888048/14419282/5df13574-fff7-11e5-8dcd-1c667053f69a.png)
![image](https://cloud.githubusercontent.com/assets/12888048/14419283/5fa0aa58-fff7-11e5-930d-b06dd47a5ac4.png)

**Comment by jsemblantetitanweb** [comment]
This is not a bug. You should enable first the manage stock so that the stock management will enable as will. Not checking the manage stock will really make the product out of stock.

**Comment by romatitan** [comment]
Plugin Issue.
If "Manage stock" is ticked, Stock Qty should have a required value otherwise, it will be displayed as Out of Stock in front-end
